# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/yumpyy"

[social.params]
icon = "brand-github"

[[social]]
identifier = "mastodon"
name = "Mastodon"
url = "https://social.linux.pizza/@hasp"

[social.params]
icon = "brand-mastodon"

[[social]]
identifier = "matrix"
name = "Matrix"
url = "https://matrix.to/#/@zrck:matrix.org"

[social.params]
icon = "brand-matrix"
