baseURL = "https://yenupam.com/"
locale = "en-us"
title = "yenupam"
theme = "not-much"
copyright = "© Anupam Roy"
enableRobotsTXT = true

[markup]
  [markup.highlight]
    style = 'dracula'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5

[params]
  theme = "light"
  palette = "default"
  showThemeNotice = false
  showPostsSummary = true
  description = "i've been breaking and building things since gpt-3. ai, linux, old hardware..."
  author = "Anupam Roy"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[menu]
  [[menu.main]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "projects"
    name = "projects"
    url = "/projects"
    weight = 2
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    url = "/posts"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about"
    weight = 4
  [[menu.main]]
    identifier = "tags"
    name = "tags"
    url = "/tags"
    weight = 5
  [[menu.main]]
    identifier = "links"
    name = "links"
    url = "/links"
    weight = 6
